default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  username: <%= ENV.fetch("DB_USER") { 'postgres' } %>
#  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'postgres' } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'tools4thought_development' } %>

test:
  <<: *default
  database: tools4thought_test

production:
  <<: *default
#  host: <%= ENV["DB_HOST"] %>
#  database: <%= ENV["DB_NAME"] %>
#  username: <%= ENV["POSTGRES_USER"] %>
#  password: <%= ENV["POSTGRES_PASSWORD"] %>
  url: <%= ENV["DATABASE_URL"] %>